---
# Basic Reboot using shell command
# File: basic_reboot.yml
- name: Reboot server using shell command
  hosts: all
  become: yes
  
  tasks:
    - name: "Execute reboot command"
      shell: reboot
      async: 1
      poll: 0
      
    - name: "Wait for server to come back"
      wait_for_connection:
        timeout: 600
        
    - name: "Wait for 3 minutes after reconnection"
      pause:
        minutes: 3
        prompt: "Waiting 3 minutes for system to stabilize after reboot..."
        
    - name: "Get server uptime"
      shell: uptime
      register: uptime_result
        
    - name: "Display reboot success and uptime"
      debug:
        msg: |
          {{ inventory_hostname }} rebooted and reconnected successfully!
          Server uptime: {{ uptime_result.stdout }}
