---
# Simple Linux Reboot Script (RECOMMENDED)
# File: reboot_server.yml
- name: Reboot Linux server
  hosts: all
  become: yes
  gather_facts: true
  
  tasks:
    - name: "Reboot the server safely"
      reboot:
        reboot_timeout: 600
        connect_timeout: 20
        test_command: uptime
      
    - name: "Wait for 3 minutes after reboot"
      pause:
        minutes: 3
        prompt: "Waiting 3 minutes after reboot for system to stabilize..."
        
    - name: "Get server uptime after reboot"
      shell: uptime
      register: server_uptime
      
    - name: "Display server uptime"
      debug:
        msg: |
          Server {{ inventory_hostname }} rebooted successfully!
          Current uptime: {{ server_uptime.stdout }}
